# Generated by Django 5.0.1 on 2024-01-23 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Сокращенное название')),
                ('fullname', models.CharField(default=None, max_length=200, verbose_name='Полное наименование конкурса')),
                ('date', models.DateField(help_text='Дата начала соревнований', verbose_name='Дата проведения')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'db_table': 'competitions',
            },
        ),
        migrations.CreateModel(
            name='CompetitionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfirst.competition')),
            ],
            options={
                'db_table': 'competition_tasks',
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('patronymic', models.CharField(default=None, max_length=25, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Удалить')),
                ('post', models.CharField(max_length=100, verbose_name='Занимаемая должность')),
                ('regalia', models.TextField(default=None, verbose_name='Заслуги и регалии')),
                ('organization', models.CharField(max_length=100, verbose_name='Место работы')),
                ('status', models.CharField(choices=[('M', 'главный судья'), ('J', 'судья'), ('S', 'секретарь'), ('O', 'наблюдатель')], default='O', max_length=1, verbose_name='Статус на соревнованиях')),
                ('competitions', models.ManyToManyField(to='appfirst.competition')),
            ],
            options={
                'db_table': 'judges',
            },
        ),
    ]
