# Generated by Django 5.0.1 on 2024-01-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfirst', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='competition',
            table='competitions',
        ),
        migrations.AlterModelTable(
            name='competitiontask',
            table='competition_tasks',
        ),
    ]
