# Generated by Django 5.0.1 on 2024-01-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfirst', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='competitions',
            field=models.ManyToManyField(blank=True, null=True, to='appfirst.competition'),
        ),
    ]
