# Generated by Django 5.0.1 on 2024-01-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfirst', '0002_alter_competition_table_alter_competitiontask_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
    ]
