# Generated by Django 5.0.1 on 2024-01-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfirst', '0003_competition_active_competition_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Удалить'),
        ),
    ]
