# Generated by Django 5.0.1 on 2024-01-19 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfirst', '0004_judge_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judge',
            old_name='competition',
            new_name='competitions',
        ),
    ]
